#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

if declare -p VIRTUAL_ENV &> /dev/null; then
    # Upgrade essancial modeles
    python -m pip install -qU pip setuptools

    # Install dev tools
    python -m pip install -qU pycodestyle pylint autopep8 pytest
fi
