#!/bin/bash
# This hook is sourced after every virtualenv is activated.

if [[ "$TERM" =~ "screen" && -n "$TMUX" ]]; then
    tmux list-windows | grep -Piq "^\d+:\s+$(basename $VIRTUAL_ENV)"
    if [ $? -eq 1 ]; then
        tmux rename-window "$(basename $VIRTUAL_ENV)"
    fi
fi

